spring:
  datasource:
    url: jdbc:mysql://${AWESOE_MEDIA_DB_SERVICE_HOST}:${AWESOME_MEDIA_DB_SERVICE_PORT}:${MYSQL_DATABAE}    
    username: ${MYSQL_USER}    
    password: ${MYSQL_PASSWORD}    
    initialize: true    
    platform: mysql   
